if [ -n "$BASH_VERSION" ]; then
	if [ -f "$HOME/.bashrc" ]; then
		source "$HOME/.bashrc"
	fi
fi

# environment variables
export EDITOR="vim"
export PATH="$HOME/bin:$PATH"

if [ -f "$HOME/.bash_profile_local" ]; then
	source "$HOME/.bash_profile_local"
fi
